-- 16-color scheme that inherits the terminal emulator's ANSI palette.
-- Requires: vim.o.termguicolors = false
--
-- Color slots (cterm 0–15) come from your terminal theme:
--   0 black          8  bright black (comments / muted)
--   1 red            9  bright red
--   2 green         10  bright green
--   3 yellow        11  bright yellow
--   4 blue          12  bright blue
--   5 magenta       13  bright magenta
--   6 cyan          14  bright cyan
--   7 white         15  bright white (foreground)

vim.cmd.highlight('clear')
if vim.fn.exists('syntax_on') == 1 then
	vim.cmd.syntax('reset')
end

vim.o.termguicolors = false
vim.g.colors_name = 'terminal'

local function hi(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

local function link(from, to)
	vim.api.nvim_set_hl(0, from, { link = to })
end

-- Core UI (bg NONE = use terminal background)
hi('Normal', { ctermfg = 7, ctermbg = 'NONE' })
hi('NormalNC', { ctermfg = 7, ctermbg = 'NONE' })
hi('NormalFloat', { ctermfg = 7, ctermbg = 'NONE' })
hi('FloatBorder', { ctermfg = 8, ctermbg = 'NONE' })
hi('FloatTitle', { ctermfg = 15, ctermbg = 'NONE', cterm = { bold = true } })

hi('Cursor', { ctermfg = 0, ctermbg = 7 })
hi('CursorLine', { ctermbg = 8 })
hi('CursorColumn', { ctermbg = 8 })
hi('CursorLineNr', { ctermfg = 15, cterm = { bold = true } })
hi('LineNr', { ctermfg = 8 })
hi('SignColumn', { ctermfg = 8, ctermbg = 'NONE' })
hi('FoldColumn', { ctermfg = 8, ctermbg = 'NONE' })
hi('Folded', { ctermfg = 8, ctermbg = 'NONE' })
hi('ColorColumn', { ctermbg = 8 })
hi('VertSplit', { ctermfg = 8, ctermbg = 'NONE' })
hi('WinSeparator', { ctermfg = 8, ctermbg = 'NONE' })

hi('StatusLine', { ctermfg = 15, ctermbg = 8, cterm = { bold = true } })
hi('StatusLineNC', { ctermfg = 7, ctermbg = 8 })
hi('TabLine', { ctermfg = 7, ctermbg = 8 })
hi('TabLineFill', { ctermbg = 8 })
hi('TabLineSel', { ctermfg = 15, ctermbg = 'NONE', cterm = { bold = true } })
hi('WinBar', { ctermfg = 15, ctermbg = 'NONE' })
hi('WinBarNC', { ctermfg = 8, ctermbg = 'NONE' })

hi('Pmenu', { ctermfg = 7, ctermbg = 8 })
hi('PmenuSel', { ctermfg = 0, ctermbg = 4 })
hi('PmenuSbar', { ctermbg = 8 })
hi('PmenuThumb', { ctermbg = 7 })
hi('WildMenu', { ctermfg = 0, ctermbg = 3 })

hi('Visual', { ctermbg = 8 })
hi('VisualNOS', { ctermbg = 8 })
hi('Search', { ctermfg = 0, ctermbg = 3 })
hi('IncSearch', { ctermfg = 0, ctermbg = 11 })
hi('CurSearch', { ctermfg = 0, ctermbg = 11 })
hi('MatchParen', { ctermfg = 15, ctermbg = 8, cterm = { bold = true } })

hi('Directory', { ctermfg = 4 })
hi('Title', { ctermfg = 5, cterm = { bold = true } })
hi('Question', { ctermfg = 2 })
hi('MoreMsg', { ctermfg = 2 })
hi('ModeMsg', { ctermfg = 7, cterm = { bold = true } })
hi('NonText', { ctermfg = 8 })
hi('SpecialKey', { ctermfg = 8 })
hi('Whitespace', { ctermfg = 8 })
hi('EndOfBuffer', { ctermfg = 8 })
hi('Conceal', { ctermfg = 8 })

hi('DiffAdd', { ctermfg = 2, ctermbg = 'NONE' })
hi('DiffChange', { ctermfg = 3, ctermbg = 'NONE' })
hi('DiffDelete', { ctermfg = 1, ctermbg = 'NONE' })
hi('DiffText', { ctermfg = 4, ctermbg = 8, cterm = { bold = true } })

hi('SpellBad', { ctermfg = 1, cterm = { underline = true } })
hi('SpellCap', { ctermfg = 4, cterm = { underline = true } })
hi('SpellLocal', { ctermfg = 6, cterm = { underline = true } })
hi('SpellRare', { ctermfg = 5, cterm = { underline = true } })

hi('ErrorMsg', { ctermfg = 1, cterm = { bold = true } })
hi('WarningMsg', { ctermfg = 3 })
hi('Todo', { ctermfg = 3, ctermbg = 'NONE', cterm = { bold = true } })
hi('Error', { ctermfg = 1 })
hi('Underlined', { ctermfg = 4, cterm = { underline = true } })

-- Syntax
hi('Comment', { ctermfg = 8, cterm = { italic = true } })
hi('Constant', { ctermfg = 1 })
hi('String', { ctermfg = 2 })
hi('Character', { ctermfg = 2 })
hi('Number', { ctermfg = 3 })
hi('Boolean', { ctermfg = 1 })
hi('Float', { ctermfg = 3 })
hi('Identifier', { ctermfg = 4 })
hi('Function', { ctermfg = 4 })
hi('Statement', { ctermfg = 5 })
hi('Conditional', { ctermfg = 5 })
hi('Repeat', { ctermfg = 5 })
hi('Label', { ctermfg = 5 })
hi('Operator', { ctermfg = 6 })
hi('Keyword', { ctermfg = 5 })
hi('Exception', { ctermfg = 1 })
hi('PreProc', { ctermfg = 6 })
hi('Include', { ctermfg = 6 })
hi('Define', { ctermfg = 6 })
hi('Macro', { ctermfg = 6 })
hi('PreCondit', { ctermfg = 6 })
hi('Type', { ctermfg = 3 })
hi('StorageClass', { ctermfg = 3 })
hi('Structure', { ctermfg = 3 })
hi('Typedef', { ctermfg = 3 })
hi('Special', { ctermfg = 6 })
hi('SpecialChar', { ctermfg = 1 })
hi('Tag', { ctermfg = 5 })
hi('Delimiter', { ctermfg = 7 })
hi('SpecialComment', { ctermfg = 8 })
hi('Debug', { ctermfg = 1 })

-- Diagnostics (LSP)
hi('DiagnosticError', { ctermfg = 1 })
hi('DiagnosticWarn', { ctermfg = 3 })
hi('DiagnosticInfo', { ctermfg = 4 })
hi('DiagnosticHint', { ctermfg = 6 })
hi('DiagnosticOk', { ctermfg = 2 })
hi('DiagnosticUnderlineError', { cterm = { underline = true } })
hi('DiagnosticUnderlineWarn', { cterm = { underline = true } })
hi('DiagnosticUnderlineInfo', { cterm = { underline = true } })
hi('DiagnosticUnderlineHint', { cterm = { underline = true } })
link('DiagnosticVirtualTextError', 'DiagnosticError')
link('DiagnosticVirtualTextWarn', 'DiagnosticWarn')
link('DiagnosticVirtualTextInfo', 'DiagnosticInfo')
link('DiagnosticVirtualTextHint', 'DiagnosticHint')
link('DiagnosticFloatingError', 'DiagnosticError')
link('DiagnosticFloatingWarn', 'DiagnosticWarn')
link('DiagnosticFloatingInfo', 'DiagnosticInfo')
link('DiagnosticFloatingHint', 'DiagnosticHint')
link('DiagnosticSignError', 'DiagnosticError')
link('DiagnosticSignWarn', 'DiagnosticWarn')
link('DiagnosticSignInfo', 'DiagnosticInfo')
link('DiagnosticSignHint', 'DiagnosticHint')

-- Treesitter → standard syntax groups
link('@comment', 'Comment')
link('@comment.documentation', 'SpecialComment')
link('@constant', 'Constant')
link('@constant.builtin', 'Constant')
link('@constant.macro', 'Define')
link('@string', 'String')
link('@string.escape', 'SpecialChar')
link('@string.special', 'SpecialChar')
link('@character', 'Character')
link('@number', 'Number')
link('@boolean', 'Boolean')
link('@float', 'Float')
link('@function', 'Function')
link('@function.builtin', 'Function')
link('@function.macro', 'Macro')
link('@function.method', 'Function')
link('@method', 'Function')
link('@constructor', 'Type')
link('@parameter', 'Identifier')
link('@variable', 'Identifier')
link('@variable.builtin', 'Identifier')
link('@variable.parameter', 'Identifier')
link('@variable.member', 'Identifier')
link('@property', 'Identifier')
link('@field', 'Identifier')
link('@type', 'Type')
link('@type.builtin', 'Type')
link('@type.definition', 'Typedef')
link('@attribute', 'PreProc')
link('@keyword', 'Keyword')
link('@keyword.function', 'Keyword')
link('@keyword.operator', 'Operator')
link('@keyword.return', 'Keyword')
link('@keyword.import', 'Include')
link('@keyword.conditional', 'Conditional')
link('@keyword.repeat', 'Repeat')
link('@keyword.exception', 'Exception')
link('@operator', 'Operator')
link('@punctuation', 'Delimiter')
link('@punctuation.delimiter', 'Delimiter')
link('@punctuation.bracket', 'Delimiter')
link('@punctuation.special', 'Special')
link('@tag', 'Tag')
link('@tag.attribute', 'Identifier')
link('@tag.delimiter', 'Delimiter')
link('@module', 'Identifier')
link('@namespace', 'Identifier')
link('@label', 'Label')
link('@markup.heading', 'Title')
link('@markup.link', 'Underlined')
link('@markup.raw', 'String')
link('@markup.strong', 'Bold')
link('@markup.italic', 'Italic')

hi('Bold', { cterm = { bold = true } })
hi('Italic', { cterm = { italic = true } })

-- Common plugin surfaces
link('TelescopeNormal', 'NormalFloat')
link('TelescopeBorder', 'FloatBorder')
link('TelescopeSelection', 'PmenuSel')
link('TelescopeMatching', 'Search')
link('WhichKey', 'Function')
link('WhichKeyGroup', 'Keyword')
link('WhichKeyDesc', 'Identifier')
link('WhichKeySeparator', 'Comment')
link('WhichKeyFloat', 'NormalFloat')
link('BlinkCmpMenu', 'Pmenu')
link('BlinkCmpMenuSelection', 'PmenuSel')
link('BlinkCmpLabelMatch', 'Search')
link('MasonHeader', 'Title')
link('MasonHighlight', 'String')
